apiVersion: v1
kind: ConfigMap
metadata:
  name: borkbot-frontend-nginx-config
data:
  default.conf: |
    server {
      listen 80;
      listen 443 ssl;
      ssl_certificate /etc/ssl/private/cert.pem;
      ssl_certificate_key /etc/ssl/private/key.pem;
      server_name  borkd-nginx-service-prod;
      location / {
        proxy_pass https://borkd-service-prod;
      }
      location / {
        access_log off;
        add_header Content-Type text/plain; # Prevents download
        return 200 "healthy\n";
      }
    }