apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: borkbot-app-deployment-prod

spec:
  selector:
    matchLabels:
      app: borkbot-app-prod
  replicas: 3
  template:
    metadata:
      labels:
        app: borkbot-app-prod

    spec:
      containers:
      - name: borkbotd
        image: gcr.io/default-project-200117/borkd:v1
        readinessProbe:
          httpGet:
            path: /borkbot/v1/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        command: ["/borkbotd"]
        args: ["--listen", ":8080", "--verification_token", "$(VERIFICATION_TOKEN)"]
        ports:
          - containerPort: 8080
            name: borkd-8080

        env:
          - name: VERIFICATION_TOKEN
            valueFrom:
              secretKeyRef:
                name: borkbot-slack
                key: verification_token
      restartPolicy: Always
